# Generated by Django 4.2.4 on 2024-01-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
