# Generated by Django 4.2.4 on 2024-01-18 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_rates_rate_post_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
